# Generated by Django 5.1.5 on 2025-02-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='defa/client.png', upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='account',
            name='job_title',
            field=models.CharField(blank=True, default='Client', max_length=255),
        ),
    ]
