# Generated by Django 5.1.5 on 2025-01-22 07:58

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=5), max_digits=5)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Larg')], default='SM', max_length=2)),
                ('image', models.ImageField(default='media/defa/defa.png', upload_to=restaurant_app.models.upload_to_dynamic)),
                ('type_of_drink', models.CharField(choices=[('HO', 'Hot'), ('CO', 'Cold')], default='CO', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=5), max_digits=5)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Larg')], default='SM', max_length=2)),
                ('image', models.ImageField(default='media/defa/defa.png', upload_to=restaurant_app.models.upload_to_dynamic)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=5), max_digits=5)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Larg')], default='SM', max_length=2)),
                ('image', models.ImageField(default='media/defa/defa.png', upload_to=restaurant_app.models.upload_to_dynamic)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sandwiches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=5), max_digits=5)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Larg')], default='SM', max_length=2)),
                ('image', models.ImageField(default='media/defa/defa.png', upload_to=restaurant_app.models.upload_to_dynamic)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
