# Generated by Django 5.1.5 on 2025-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='restaurant', max_length=255)),
                ('address', models.CharField(default='address', max_length=255)),
                ('phone_number', models.CharField(default='phone_number', max_length=20)),
                ('email', models.EmailField(default='email', max_length=255)),
                ('image', models.ImageField(default='media/defa/defa', upload_to='restaurant/')),
            ],
        ),
    ]
