# Generated by Django 5.1.5 on 2025-01-23 07:28

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_rest_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=5), max_digits=5)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Larg')], default='SM', max_length=2)),
                ('image', models.ImageField(default='media/defa/defa.png', upload_to=restaurant_app.models.upload_to_dynamic)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
