# Generated by Django 5.1.5 on 2025-01-23 08:09

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_sweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chef', max_length=255)),
                ('description', models.CharField(default='description Chef', max_length=4000)),
                ('image', models.ImageField(default='media/defa/chef.jpg', upload_to='chef/')),
                ('facebook', models.URLField(blank=True, default='', help_text="URL to the chef's Facebook profile", max_length=500)),
                ('instagram', models.URLField(blank=True, default='', help_text="URL to the chef's Instagram profile", max_length=500)),
                ('twitter', models.URLField(blank=True, default='', help_text="URL to the chef's Twitter profile", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chef', max_length=255)),
                ('description', models.CharField(default='description Chef', max_length=4000)),
                ('image', models.ImageField(default='media/defa/client.png', upload_to='chef/')),
                ('message', models.CharField(default='Chef', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=5), max_digits=5)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Larg')], default='SM', max_length=2)),
                ('image', models.ImageField(default='media/defa/defa.png', upload_to=restaurant_app.models.upload_to_dynamic)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rest_detail',
            name='image',
            field=models.ImageField(default='media/defa/defa.png', upload_to='restaurant/'),
        ),
    ]
