# Generated by Django 5.1.5 on 2025-01-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_chefs_clients_salads_alter_rest_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Service', max_length=50)),
                ('description', models.CharField(default='description of services', max_length=2500)),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
    ]
