# Generated by Django 5.1.5 on 2025-01-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_one', models.CharField(max_length=2500)),
                ('paragraph_two', models.CharField(max_length=2500)),
                ('experience_years', models.PositiveIntegerField(default=15)),
                ('master_chefs', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us_images/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurant_app.aboutus')),
            ],
        ),
    ]
