# Generated by Django 5.1.5 on 2025-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_clients_options_clients_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='grills',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='meals',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='salads',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='sandwiches',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='sweets',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
