# Generated by Django 5.1.5 on 2025-01-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_drinks_description_grills_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='category',
            field=models.CharField(default='drinks', max_length=250),
        ),
        migrations.AddField(
            model_name='grills',
            name='category',
            field=models.CharField(default='drinks', max_length=250),
        ),
        migrations.AddField(
            model_name='meals',
            name='category',
            field=models.CharField(default='drinks', max_length=250),
        ),
        migrations.AddField(
            model_name='salads',
            name='category',
            field=models.CharField(default='drinks', max_length=250),
        ),
        migrations.AddField(
            model_name='sandwiches',
            name='category',
            field=models.CharField(default='drinks', max_length=250),
        ),
        migrations.AddField(
            model_name='sweets',
            name='category',
            field=models.CharField(default='drinks', max_length=250),
        ),
    ]
