# Generated by Django 5.1.5 on 2025-02-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0012_alter_chefs_image_alter_clients_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='category',
            field=models.CharField(default='food_menu', max_length=250),
        ),
        migrations.AlterField(
            model_name='grills',
            name='category',
            field=models.CharField(default='food_menu', max_length=250),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.CharField(default='food_menu', max_length=250),
        ),
        migrations.AlterField(
            model_name='salads',
            name='category',
            field=models.CharField(default='food_menu', max_length=250),
        ),
        migrations.AlterField(
            model_name='sandwiches',
            name='category',
            field=models.CharField(default='food_menu', max_length=250),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='category',
            field=models.CharField(default='food_menu', max_length=250),
        ),
    ]
