# Generated by Django 5.1.5 on 2025-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_alter_drinks_category_alter_grills_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_email', models.EmailField(default='anas227sultan@gmail.com', max_length=254)),
                ('General_email', models.EmailField(default='anas227sultan@gmail.com', max_length=254)),
                ('Technical_email', models.EmailField(default='anas227sultan@gmail.com', max_length=254)),
            ],
        ),
    ]
