# Generated by Django 5.1.5 on 2025-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0014_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='General_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Technical_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='general_email',
            field=models.EmailField(default='anas227sultan@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='technical_email',
            field=models.EmailField(default='anas227sultan@gmail.com', max_length=254),
        ),
    ]
