# Generated by Django 5.1.5 on 2025-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0015_remove_contact_general_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_detail',
            name='description1',
            field=models.CharField(default='Enjoy OurDelicious Meal', max_length=255),
        ),
        migrations.AddField(
            model_name='rest_detail',
            name='description2',
            field=models.CharField(default='Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet', max_length=1500),
        ),
    ]
