# Generated by Django 5.1.5 on 2025-02-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0016_rest_detail_description1_rest_detail_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grills',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sandwiches',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sweets',
            name='category',
        ),
    ]
