# Generated by Django 5.1.5 on 2025-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0017_remove_drinks_category_remove_grills_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=6), max_digits=6),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grills',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=6), max_digits=6),
        ),
        migrations.AlterField(
            model_name='grills',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='meals',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=6), max_digits=6),
        ),
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='salads',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=6), max_digits=6),
        ),
        migrations.AlterField(
            model_name='salads',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sandwiches',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=6), max_digits=6),
        ),
        migrations.AlterField(
            model_name='sandwiches',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=6), max_digits=6),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
