# Generated by Django 5.1.5 on 2025-02-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0018_alter_drinks_last_price_alter_drinks_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2)),
                ('food_type', models.CharField(choices=[('Drinks', 'Drinks'), ('Meals', 'Meals'), ('Sandwiches', 'Sandwiches'), ('Grills', 'Grills'), ('Sweets', 'Sweets'), ('Salads', 'Salads')], max_length=20)),
                ('food_id', models.PositiveIntegerField()),
                ('calculated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='restaurant_app.cartitem')),
            ],
        ),
    ]
