# Generated by Django 5.1.5 on 2025-02-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0019_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='grills',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='meals',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='salads',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='sandwiches',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
    ]
