# Generated by Django 5.1.5 on 2025-02-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0021_drinks_large_price_drinks_medium_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], max_length=2, null=True),
        ),
    ]
