# Generated by Django 5.1.5 on 2025-02-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0023_remove_drinks_last_price_remove_grills_last_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
