# Generated by Django 5.1.5 on 2025-02-26 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0025_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizePriceMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2)),
                ('small_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('medium_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='large_price',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='medium_price',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='size',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='small_price',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='large_price',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='medium_price',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='size',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='small_price',
        ),
        migrations.AddField(
            model_name='drinks',
            name='sizepricemixin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant_app.sizepricemixin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salads',
            name='sizepricemixin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant_app.sizepricemixin'),
            preserve_default=False,
        ),
    ]
