# Generated by Django 5.1.5 on 2025-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0026_sizepricemixin_remove_drinks_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salads',
            name='sizepricemixin_ptr',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='sizepricemixin_ptr',
        ),
        migrations.AddField(
            model_name='drinks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=70, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinks',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='drinks',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='drinks',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AddField(
            model_name='drinks',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salads',
            name='id',
            field=models.BigAutoField(auto_created=True, default=72, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salads',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salads',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salads',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='SM', max_length=2),
        ),
        migrations.AddField(
            model_name='salads',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='SizePriceMixin',
        ),
    ]
