# Generated by Django 5.1.5 on 2025-03-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0029_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='general_whatsapp',
            field=models.CharField(default='+972594073606', max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(default='+970594073606', max_length=15),
        ),
    ]
