# Generated by Django 5.1.5 on 2025-03-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0031_remove_contact_telegram_contact_telegram_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='general_whatsapp',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
