# Generated by Django 5.1.5 on 2025-03-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0035_cart_phone_cart_state_cart_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='street',
        ),
    ]
