# Generated by Django 5.1.5 on 2025-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0036_remove_cart_phone_remove_cart_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
