# Generated by Django 5.1.5 on 2025-03-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0039_cart_secret_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_detail',
            name='background_image_url',
            field=models.ImageField(default='defa/background.png', upload_to='restaurant/backgrounds/'),
        ),
        migrations.AddField(
            model_name='rest_detail',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=LXNdRCjZt00&t=19s'),
        ),
    ]
