# Generated by Django 5.1.5 on 2025-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0040_rest_detail_background_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_detail',
            name='backend_url',
            field=models.URLField(default='https://anasabusultan.pythonanywhere.com/Anas-Abu-Sultan/'),
        ),
    ]
